image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

stages:
  - build

build-job:
  stage: build
  image: docker:dind
  script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD
    - docker build -t broc1603/game-stat-web-app --build-arg base_url=$REACT_APP_BASE_URL .
    - docker push broc1603/game-stat-web-app
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
